/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_qwics_jdbc_jni_QwicsTPMServerWrapper */

#ifndef _Included_org_qwics_jdbc_jni_QwicsTPMServerWrapper
#define _Included_org_qwics_jdbc_jni_QwicsTPMServerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_qwics_jdbc_jni_QwicsTPMServerWrapper
 * Method:    execCallback
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_qwics_jdbc_jni_QwicsTPMServerWrapper_execCallback
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
