/***
 * Generated by: P3/COBOL 17.0.0-SNAPSHOT (17.0.0-8a299c8 [Build #692])
 * Time: 16:46:19.22
 * Date: 11/17/23
 * Source: EXEC_TESTBR.COB
 */
package programs;
import com.turrettech.p3cobol.lib.*;
import com.turrettech.p3cobol.lib.annotations.*;
import com.turrettech.p3cobol.lib.common.*;
import com.turrettech.p3cobol.lib.common.DataConstants.*;
import com.turrettech.p3cobol.lib.common.DataUtil.*;
import com.turrettech.p3cobol.lib.common.exceptions.*;
import com.turrettech.p3cobol.lib.common.files.*;
import com.turrettech.p3cobol.lib.common.files.KeyDescriptor.*;
import com.turrettech.p3cobol.lib.common.systemnames.*;
import com.turrettech.p3cobol.lib.devices.*;
import com.turrettech.p3cobol.lib.devices.terminal.*;
import com.turrettech.p3cobol.lib.exceptions.*;
import com.turrettech.p3cobol.lib.exceptions.AcceptEscapeException.*;
import com.turrettech.p3cobol.lib.files.*;
import com.turrettech.p3cobol.lib.files.FileConnector.*;
import com.turrettech.p3cobol.lib.files.internal.sort.*;
import com.turrettech.p3cobol.lib.sql.*;
import com.turrettech.p3cobol.lib.sql.exceptions.*;
import com.turrettech.p3cobol.lib.string.*;
import com.turrettech.p3cobol.lib.xml.*;
import data.testbr.Ctpty;
import data.testbr.Dfheiblk;
import java.io.ByteArrayInputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.io.Writer;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.List;
import java.util.TreeMap;
import java.util.regex.Pattern;
import javax.xml.parsers.SAXParser;
import javax.xml.transform.sax.SAXResult;
import javax.xml.transform.sax.SAXTransformerFactory;
import javax.xml.transform.sax.TransformerHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.ContentHandler;
import org.xml.sax.InputSource;
import org.xml.sax.XMLReader;

@ProgramAttributes(name="testbr", id={-1}, entries={})
public final class Testbr extends Program {
	public static final String getCompilationDate() { return "2023111716461909+0100"; }
	public static final String getCompilationVersion() { return "17.0.0-SNAPSHOT (17.0.0-8a299c8 [Build #692])"; }
	@Override
	public final String getName() { return "TESTBR"; }
	@Override
	public final String[] getEntryNames() { return new String[]{}; }
	@Override
	public final boolean isDecimalPointComma() { return false; }
	@Override
	public final int getPointerSize() { return 8; }
	@Override
	public final char getCurrencySymbol() { return '$'; }
	@Override
	public final DecimalZoneType getDecimalZoneType() { return DecimalZoneType.ASCII; }
	private final CobolComparator __compare = new CobolComparator();
	@Override
	public final CobolComparator getComparator() { return __compare; }
	protected final CobolMath cobolMath = getDataUtil().cobolMath;
	private static final Logger LOGGER = LoggerFactory.getLogger(Testbr.class);
	public static void main(String[] args) {
		try (RunUnit runUnit = RunUnit.currentThreadRunUnitForced()) {
			runUnit.run("programs.Testbr", null, (Object[])args);
		} catch (P3ExitException e) {
			System.exit((int)e.getReturnCode());
		} catch (P3RuntimeException e) {
			LOGGER.error("unexpected P3 exception: ", e);
			throw e;
		}
	}
	private final int getFirstProcedure() { return 6/*_nemo_1_*/; }
	private int _nemo() {
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:SET DFHEIBLK",get_Dfheiblk__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:SET EIBCALEN",get_Eibcalen__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:SET EIBAID",get_Eibaid__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:EXEC",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:CICS",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:STARTBR",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:FILE",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:'AWS.TEST.DB'",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:REQID",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:",1);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP",get_Ws_resp__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP2",get_Ws_resp2__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:END-EXEC.",null);
		}
		while (DataConstants.TRUE && !((((get_Ws_resp() > 0))))) {
			if (perform(8/*Read_data*/, 9/*phantom*/)) return ProcedureAttributes.EXIT_PROGRAM;
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:EXEC",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:CICS",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:ENDBR",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:FILE",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:'AWS.TEST.DB'",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:REQID",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:",1);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP",get_Ws_resp__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP2",get_Ws_resp2__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:END-EXEC.",null);
		}
		return ProcedureAttributes.EXIT_PROGRAM;
	}
	private int read_data() {
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:EXEC",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:CICS",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:READNEXT",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:FILE",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:'AWS.TEST.DB'",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:REQID",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:",1);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:INTO",null);
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:",get_Ctpty__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:LENGTH",null);
		}
		set_Qwicslen(49);
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:",get_Qwicslen__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP",get_Ws_resp__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:RESP2",get_Ws_resp2__Pointer());
		}
		java: {
			               
			 org.qwics.jni.QwicsTPMServerWrapper.getInstance()                   
			.execCallback("TPMI:END-EXEC.",null);
		}
		getEnvironmentDatasource(EnvironmentAccessor.CONSOLE).outputLineTo(CharBuffer.wrap(getComparator().getCharset().decode(getLiteral(1,10/* "READ RESP " */)).toString()/* NARROWS */+String.valueOf(get_Ws_resp())+getComparator().getCharset().decode(getLiteral(11,1/* " " */)).toString()/* NARROWS */+String.valueOf(get_Ws_resp2())));
		getEnvironmentDatasource(EnvironmentAccessor.CONSOLE).outputLineTo(CharBuffer.wrap(getComparator().getCharset().decode(ctpty.get_Matchcode()).toString()/* NARROWS */+getComparator().getCharset().decode(getLiteral(12,1/* "*" */)).toString()/* NARROWS */+getComparator().getCharset().decode(ctpty.get_Bezeichnung()).toString()/* NARROWS */+getComparator().getCharset().decode(getLiteral(13,1/* "*" */)).toString()/* NARROWS */+com.turrettech.p3cobol.lib.Decimal.toString(ctpty.get_Tageslimit())));
		return 0;
	}
	public void cancel() {
		if (isInitialized) {
			isInitialized = false;
		}
	}
	public Object execute(Object... args) {
		return execute_(
			() -> {
				return (CobolPointer[]) null;
			}, 
			() -> {
				initialize(); 
				try {
					if (getCobolPointerArg(1) != null) {
						set_Dfhcommarea__Base(getCobolPointerArg(1));
					}
				} catch (P3ArgumentException pae) {
					set_Dfhcommarea__Base();
					set_Dfhcommarea(getByteBufferArg(1,1));
				}
				perform(getFirstProcedure(), -1);
				doCobolReturn();
				return get_Return_code();
			}, 
			(stackFrame) -> {
			}
			, args
		);
	}
	private boolean perform(int gotoTarget, int terminalProcedure) {
		while (true) {
			switch(gotoTarget) {
				case -1: { return true; }
				case -6:
				case 6/*_nemo_1_*/:
					if (_nemo() == -1) return true;
					if (6 == terminalProcedure) return false;
				case -8:
				case 8/*Read_data*/:
					read_data();
					if (8 == terminalProcedure) return false;
				case -9:
				case 9/*phantom*/:
					if (9 == terminalProcedure) return false;
				default:
					return false;
			}
		}
	}
	private final Partition __partition[] = new Partition[0];
	public void set_Return_code(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(0, 4, val, 0);;
			_return_code__isValid = false;
		} else {
			set_Return_code(((Number)o).intValue());
		}
	}
	public int get_Return_code() {
		if (!_return_code__isValid) { _return_code = super.getBinaryIntUNO(0,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _return_code__isValid = true; _return_code__isCoherent = true;  } return _return_code;
	}
	public int set_Return_code(int val) {
		val = super.truncate( 9, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._return_code = val; _return_code__isValid = true; _return_code__isCoherent = false; return val; 
	}
	public final void synchronize_Return_code() {if (_return_code__isValid && !_return_code__isCoherent) { _return_code__isCoherent = true; super.setBinaryNormalized(0, 9, _return_code, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _return_code; public boolean _return_code__isValid; private boolean _return_code__isCoherent;
	public void set_Qwicsptr(ByteBuffer val) {
		super.setBytes(4, 8, val, 0);;
	}
	public CobolPointer get_Qwicsptr() {
		return super.getPointer(4,8);
	}
	public void set_Qwicsptr(CobolPointer val) {
		super.setBytes(4, 8, ((val != null) ? val.get(8) : new byte[]{0,0,0,0,0,0,0,0}));
	}
	public void set_Qwicslen(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(12, 9, val, 0);;
			_qwicslen__isValid = false;
		} else {
			set_Qwicslen(((Number)o).intValue());
		}
	}
	public int get_Qwicslen() {
		if (!_qwicslen__isValid) { _qwicslen = super.getDisplayInt(12,9,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NSU); _qwicslen__isValid = true; _qwicslen__isCoherent = true;  } return _qwicslen;
	}
	public int set_Qwicslen(int val) {
		val = super.truncate(9, val,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NSU); this._qwicslen = val; _qwicslen__isValid = true; _qwicslen__isCoherent = false; return val; 
	}
	public final void synchronize_Qwicslen() {if (_qwicslen__isValid && !_qwicslen__isCoherent) { _qwicslen__isCoherent = true; super.setDisplayNormalized(12,9, _qwicslen,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NSU);} } public int _qwicslen; public boolean _qwicslen__isValid; private boolean _qwicslen__isCoherent;
	public CobolPointer get_Qwicslen__Pointer() {
		return super.pointerTo(12,9, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NSU,9,0);
	}
	public CobolPointer get_Qwicslen__Pointer(int offset, int length) {
		return super.pointerTo(12 + offset,Math.min(9 - offset, length), com.turrettech.p3cobol.lib.common.DataConstants.CobolType.GRP);
	}
	public void set_Dfhresp_normal(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(221, 4, val, 0);;
			_dfhresp_normal__isValid = false;
		} else {
			set_Dfhresp_normal(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_normal() {
		if (!_dfhresp_normal__isValid) { _dfhresp_normal = super.getBinaryIntUNO(221,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_normal__isValid = true; _dfhresp_normal__isCoherent = true;  } return _dfhresp_normal;
	}
	public int set_Dfhresp_normal(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_normal = val; _dfhresp_normal__isValid = true; _dfhresp_normal__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_normal() {if (_dfhresp_normal__isValid && !_dfhresp_normal__isCoherent) { _dfhresp_normal__isCoherent = true; super.setBinaryNormalized(221, 8, _dfhresp_normal, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_normal; public boolean _dfhresp_normal__isValid; private boolean _dfhresp_normal__isCoherent;
	public void set_Dfhresp_duprec(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(225, 4, val, 0);;
			_dfhresp_duprec__isValid = false;
		} else {
			set_Dfhresp_duprec(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_duprec() {
		if (!_dfhresp_duprec__isValid) { _dfhresp_duprec = super.getBinaryIntUNO(225,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_duprec__isValid = true; _dfhresp_duprec__isCoherent = true;  } return _dfhresp_duprec;
	}
	public int set_Dfhresp_duprec(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_duprec = val; _dfhresp_duprec__isValid = true; _dfhresp_duprec__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_duprec() {if (_dfhresp_duprec__isValid && !_dfhresp_duprec__isCoherent) { _dfhresp_duprec__isCoherent = true; super.setBinaryNormalized(225, 8, _dfhresp_duprec, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_duprec; public boolean _dfhresp_duprec__isValid; private boolean _dfhresp_duprec__isCoherent;
	public void set_Dfhresp_dupkey(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(229, 4, val, 0);;
			_dfhresp_dupkey__isValid = false;
		} else {
			set_Dfhresp_dupkey(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_dupkey() {
		if (!_dfhresp_dupkey__isValid) { _dfhresp_dupkey = super.getBinaryIntUNO(229,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_dupkey__isValid = true; _dfhresp_dupkey__isCoherent = true;  } return _dfhresp_dupkey;
	}
	public int set_Dfhresp_dupkey(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_dupkey = val; _dfhresp_dupkey__isValid = true; _dfhresp_dupkey__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_dupkey() {if (_dfhresp_dupkey__isValid && !_dfhresp_dupkey__isCoherent) { _dfhresp_dupkey__isCoherent = true; super.setBinaryNormalized(229, 8, _dfhresp_dupkey, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_dupkey; public boolean _dfhresp_dupkey__isValid; private boolean _dfhresp_dupkey__isCoherent;
	public void set_Dfhresp_invreq(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(233, 4, val, 0);;
			_dfhresp_invreq__isValid = false;
		} else {
			set_Dfhresp_invreq(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_invreq() {
		if (!_dfhresp_invreq__isValid) { _dfhresp_invreq = super.getBinaryIntUNO(233,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_invreq__isValid = true; _dfhresp_invreq__isCoherent = true;  } return _dfhresp_invreq;
	}
	public int set_Dfhresp_invreq(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_invreq = val; _dfhresp_invreq__isValid = true; _dfhresp_invreq__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_invreq() {if (_dfhresp_invreq__isValid && !_dfhresp_invreq__isCoherent) { _dfhresp_invreq__isCoherent = true; super.setBinaryNormalized(233, 8, _dfhresp_invreq, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_invreq; public boolean _dfhresp_invreq__isValid; private boolean _dfhresp_invreq__isCoherent;
	public void set_Dfhresp_endfile(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(237, 4, val, 0);;
			_dfhresp_endfile__isValid = false;
		} else {
			set_Dfhresp_endfile(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_endfile() {
		if (!_dfhresp_endfile__isValid) { _dfhresp_endfile = super.getBinaryIntUNO(237,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_endfile__isValid = true; _dfhresp_endfile__isCoherent = true;  } return _dfhresp_endfile;
	}
	public int set_Dfhresp_endfile(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_endfile = val; _dfhresp_endfile__isValid = true; _dfhresp_endfile__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_endfile() {if (_dfhresp_endfile__isValid && !_dfhresp_endfile__isCoherent) { _dfhresp_endfile__isCoherent = true; super.setBinaryNormalized(237, 8, _dfhresp_endfile, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_endfile; public boolean _dfhresp_endfile__isValid; private boolean _dfhresp_endfile__isCoherent;
	public void set_Dfhresp_lengerr(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(241, 4, val, 0);;
			_dfhresp_lengerr__isValid = false;
		} else {
			set_Dfhresp_lengerr(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_lengerr() {
		if (!_dfhresp_lengerr__isValid) { _dfhresp_lengerr = super.getBinaryIntUNO(241,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_lengerr__isValid = true; _dfhresp_lengerr__isCoherent = true;  } return _dfhresp_lengerr;
	}
	public int set_Dfhresp_lengerr(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_lengerr = val; _dfhresp_lengerr__isValid = true; _dfhresp_lengerr__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_lengerr() {if (_dfhresp_lengerr__isValid && !_dfhresp_lengerr__isCoherent) { _dfhresp_lengerr__isCoherent = true; super.setBinaryNormalized(241, 8, _dfhresp_lengerr, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_lengerr; public boolean _dfhresp_lengerr__isValid; private boolean _dfhresp_lengerr__isCoherent;
	public void set_Dfhresp_qiderr(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(245, 4, val, 0);;
			_dfhresp_qiderr__isValid = false;
		} else {
			set_Dfhresp_qiderr(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_qiderr() {
		if (!_dfhresp_qiderr__isValid) { _dfhresp_qiderr = super.getBinaryIntUNO(245,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_qiderr__isValid = true; _dfhresp_qiderr__isCoherent = true;  } return _dfhresp_qiderr;
	}
	public int set_Dfhresp_qiderr(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_qiderr = val; _dfhresp_qiderr__isValid = true; _dfhresp_qiderr__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_qiderr() {if (_dfhresp_qiderr__isValid && !_dfhresp_qiderr__isCoherent) { _dfhresp_qiderr__isCoherent = true; super.setBinaryNormalized(245, 8, _dfhresp_qiderr, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_qiderr; public boolean _dfhresp_qiderr__isValid; private boolean _dfhresp_qiderr__isCoherent;
	public void set_Dfhresp_notfnd(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(249, 4, val, 0);;
			_dfhresp_notfnd__isValid = false;
		} else {
			set_Dfhresp_notfnd(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_notfnd() {
		if (!_dfhresp_notfnd__isValid) { _dfhresp_notfnd = super.getBinaryIntUNO(249,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_notfnd__isValid = true; _dfhresp_notfnd__isCoherent = true;  } return _dfhresp_notfnd;
	}
	public int set_Dfhresp_notfnd(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_notfnd = val; _dfhresp_notfnd__isValid = true; _dfhresp_notfnd__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_notfnd() {if (_dfhresp_notfnd__isValid && !_dfhresp_notfnd__isCoherent) { _dfhresp_notfnd__isCoherent = true; super.setBinaryNormalized(249, 8, _dfhresp_notfnd, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_notfnd; public boolean _dfhresp_notfnd__isValid; private boolean _dfhresp_notfnd__isCoherent;
	public void set_Dfhresp_pgmiderr(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(253, 4, val, 0);;
			_dfhresp_pgmiderr__isValid = false;
		} else {
			set_Dfhresp_pgmiderr(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_pgmiderr() {
		if (!_dfhresp_pgmiderr__isValid) { _dfhresp_pgmiderr = super.getBinaryIntUNO(253,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_pgmiderr__isValid = true; _dfhresp_pgmiderr__isCoherent = true;  } return _dfhresp_pgmiderr;
	}
	public int set_Dfhresp_pgmiderr(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_pgmiderr = val; _dfhresp_pgmiderr__isValid = true; _dfhresp_pgmiderr__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_pgmiderr() {if (_dfhresp_pgmiderr__isValid && !_dfhresp_pgmiderr__isCoherent) { _dfhresp_pgmiderr__isCoherent = true; super.setBinaryNormalized(253, 8, _dfhresp_pgmiderr, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_pgmiderr; public boolean _dfhresp_pgmiderr__isValid; private boolean _dfhresp_pgmiderr__isCoherent;
	public void set_Dfhresp_itemerr(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(257, 4, val, 0);;
			_dfhresp_itemerr__isValid = false;
		} else {
			set_Dfhresp_itemerr(((Number)o).intValue());
		}
	}
	public int get_Dfhresp_itemerr() {
		if (!_dfhresp_itemerr__isValid) { _dfhresp_itemerr = super.getBinaryIntUNO(257,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhresp_itemerr__isValid = true; _dfhresp_itemerr__isCoherent = true;  } return _dfhresp_itemerr;
	}
	public int set_Dfhresp_itemerr(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhresp_itemerr = val; _dfhresp_itemerr__isValid = true; _dfhresp_itemerr__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhresp_itemerr() {if (_dfhresp_itemerr__isValid && !_dfhresp_itemerr__isCoherent) { _dfhresp_itemerr__isCoherent = true; super.setBinaryNormalized(257, 8, _dfhresp_itemerr, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhresp_itemerr; public boolean _dfhresp_itemerr__isValid; private boolean _dfhresp_itemerr__isCoherent;
	public void set_Dfhvalue_client(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(261, 4, val, 0);;
			_dfhvalue_client__isValid = false;
		} else {
			set_Dfhvalue_client(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_client() {
		if (!_dfhvalue_client__isValid) { _dfhvalue_client = super.getBinaryIntUNO(261,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_client__isValid = true; _dfhvalue_client__isCoherent = true;  } return _dfhvalue_client;
	}
	public int set_Dfhvalue_client(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_client = val; _dfhvalue_client__isValid = true; _dfhvalue_client__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_client() {if (_dfhvalue_client__isValid && !_dfhvalue_client__isCoherent) { _dfhvalue_client__isCoherent = true; super.setBinaryNormalized(261, 8, _dfhvalue_client, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_client; public boolean _dfhvalue_client__isValid; private boolean _dfhvalue_client__isCoherent;
	public void set_Dfhvalue_sender(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(265, 4, val, 0);;
			_dfhvalue_sender__isValid = false;
		} else {
			set_Dfhvalue_sender(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_sender() {
		if (!_dfhvalue_sender__isValid) { _dfhvalue_sender = super.getBinaryIntUNO(265,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_sender__isValid = true; _dfhvalue_sender__isCoherent = true;  } return _dfhvalue_sender;
	}
	public int set_Dfhvalue_sender(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_sender = val; _dfhvalue_sender__isValid = true; _dfhvalue_sender__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_sender() {if (_dfhvalue_sender__isValid && !_dfhvalue_sender__isCoherent) { _dfhvalue_sender__isCoherent = true; super.setBinaryNormalized(265, 8, _dfhvalue_sender, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_sender; public boolean _dfhvalue_sender__isValid; private boolean _dfhvalue_sender__isCoherent;
	public void set_Dfhvalue_log(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(269, 4, val, 0);;
			_dfhvalue_log__isValid = false;
		} else {
			set_Dfhvalue_log(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_log() {
		if (!_dfhvalue_log__isValid) { _dfhvalue_log = super.getBinaryIntUNO(269,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_log__isValid = true; _dfhvalue_log__isCoherent = true;  } return _dfhvalue_log;
	}
	public int set_Dfhvalue_log(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_log = val; _dfhvalue_log__isValid = true; _dfhvalue_log__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_log() {if (_dfhvalue_log__isValid && !_dfhvalue_log__isCoherent) { _dfhvalue_log__isCoherent = true; super.setBinaryNormalized(269, 8, _dfhvalue_log, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_log; public boolean _dfhvalue_log__isValid; private boolean _dfhvalue_log__isCoherent;
	public void set_Dfhvalue_nolog(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(273, 4, val, 0);;
			_dfhvalue_nolog__isValid = false;
		} else {
			set_Dfhvalue_nolog(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_nolog() {
		if (!_dfhvalue_nolog__isValid) { _dfhvalue_nolog = super.getBinaryIntUNO(273,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_nolog__isValid = true; _dfhvalue_nolog__isCoherent = true;  } return _dfhvalue_nolog;
	}
	public int set_Dfhvalue_nolog(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_nolog = val; _dfhvalue_nolog__isValid = true; _dfhvalue_nolog__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_nolog() {if (_dfhvalue_nolog__isValid && !_dfhvalue_nolog__isCoherent) { _dfhvalue_nolog__isCoherent = true; super.setBinaryNormalized(273, 8, _dfhvalue_nolog, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_nolog; public boolean _dfhvalue_nolog__isValid; private boolean _dfhvalue_nolog__isCoherent;
	public void set_Dfhvalue_readable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(277, 4, val, 0);;
			_dfhvalue_readable__isValid = false;
		} else {
			set_Dfhvalue_readable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_readable() {
		if (!_dfhvalue_readable__isValid) { _dfhvalue_readable = super.getBinaryIntUNO(277,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_readable__isValid = true; _dfhvalue_readable__isCoherent = true;  } return _dfhvalue_readable;
	}
	public int set_Dfhvalue_readable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_readable = val; _dfhvalue_readable__isValid = true; _dfhvalue_readable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_readable() {if (_dfhvalue_readable__isValid && !_dfhvalue_readable__isCoherent) { _dfhvalue_readable__isCoherent = true; super.setBinaryNormalized(277, 8, _dfhvalue_readable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_readable; public boolean _dfhvalue_readable__isValid; private boolean _dfhvalue_readable__isCoherent;
	public void set_Dfhvalue_notreadable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(281, 4, val, 0);;
			_dfhvalue_notreadable__isValid = false;
		} else {
			set_Dfhvalue_notreadable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_notreadable() {
		if (!_dfhvalue_notreadable__isValid) { _dfhvalue_notreadable = super.getBinaryIntUNO(281,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_notreadable__isValid = true; _dfhvalue_notreadable__isCoherent = true;  } return _dfhvalue_notreadable;
	}
	public int set_Dfhvalue_notreadable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_notreadable = val; _dfhvalue_notreadable__isValid = true; _dfhvalue_notreadable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_notreadable() {if (_dfhvalue_notreadable__isValid && !_dfhvalue_notreadable__isCoherent) { _dfhvalue_notreadable__isCoherent = true; super.setBinaryNormalized(281, 8, _dfhvalue_notreadable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_notreadable; public boolean _dfhvalue_notreadable__isValid; private boolean _dfhvalue_notreadable__isCoherent;
	public void set_Dfhvalue_updatable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(285, 4, val, 0);;
			_dfhvalue_updatable__isValid = false;
		} else {
			set_Dfhvalue_updatable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_updatable() {
		if (!_dfhvalue_updatable__isValid) { _dfhvalue_updatable = super.getBinaryIntUNO(285,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_updatable__isValid = true; _dfhvalue_updatable__isCoherent = true;  } return _dfhvalue_updatable;
	}
	public int set_Dfhvalue_updatable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_updatable = val; _dfhvalue_updatable__isValid = true; _dfhvalue_updatable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_updatable() {if (_dfhvalue_updatable__isValid && !_dfhvalue_updatable__isCoherent) { _dfhvalue_updatable__isCoherent = true; super.setBinaryNormalized(285, 8, _dfhvalue_updatable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_updatable; public boolean _dfhvalue_updatable__isValid; private boolean _dfhvalue_updatable__isCoherent;
	public void set_Dfhvalue_notupdble(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(289, 4, val, 0);;
			_dfhvalue_notupdble__isValid = false;
		} else {
			set_Dfhvalue_notupdble(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_notupdble() {
		if (!_dfhvalue_notupdble__isValid) { _dfhvalue_notupdble = super.getBinaryIntUNO(289,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_notupdble__isValid = true; _dfhvalue_notupdble__isCoherent = true;  } return _dfhvalue_notupdble;
	}
	public int set_Dfhvalue_notupdble(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_notupdble = val; _dfhvalue_notupdble__isValid = true; _dfhvalue_notupdble__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_notupdble() {if (_dfhvalue_notupdble__isValid && !_dfhvalue_notupdble__isCoherent) { _dfhvalue_notupdble__isCoherent = true; super.setBinaryNormalized(289, 8, _dfhvalue_notupdble, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_notupdble; public boolean _dfhvalue_notupdble__isValid; private boolean _dfhvalue_notupdble__isCoherent;
	public void set_Dfhvalue_ctrlable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(293, 4, val, 0);;
			_dfhvalue_ctrlable__isValid = false;
		} else {
			set_Dfhvalue_ctrlable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_ctrlable() {
		if (!_dfhvalue_ctrlable__isValid) { _dfhvalue_ctrlable = super.getBinaryIntUNO(293,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_ctrlable__isValid = true; _dfhvalue_ctrlable__isCoherent = true;  } return _dfhvalue_ctrlable;
	}
	public int set_Dfhvalue_ctrlable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_ctrlable = val; _dfhvalue_ctrlable__isValid = true; _dfhvalue_ctrlable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_ctrlable() {if (_dfhvalue_ctrlable__isValid && !_dfhvalue_ctrlable__isCoherent) { _dfhvalue_ctrlable__isCoherent = true; super.setBinaryNormalized(293, 8, _dfhvalue_ctrlable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_ctrlable; public boolean _dfhvalue_ctrlable__isValid; private boolean _dfhvalue_ctrlable__isCoherent;
	public void set_Dfhvalue_notctrlable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(297, 4, val, 0);;
			_dfhvalue_notctrlable__isValid = false;
		} else {
			set_Dfhvalue_notctrlable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_notctrlable() {
		if (!_dfhvalue_notctrlable__isValid) { _dfhvalue_notctrlable = super.getBinaryIntUNO(297,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_notctrlable__isValid = true; _dfhvalue_notctrlable__isCoherent = true;  } return _dfhvalue_notctrlable;
	}
	public int set_Dfhvalue_notctrlable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_notctrlable = val; _dfhvalue_notctrlable__isValid = true; _dfhvalue_notctrlable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_notctrlable() {if (_dfhvalue_notctrlable__isValid && !_dfhvalue_notctrlable__isCoherent) { _dfhvalue_notctrlable__isCoherent = true; super.setBinaryNormalized(297, 8, _dfhvalue_notctrlable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_notctrlable; public boolean _dfhvalue_notctrlable__isValid; private boolean _dfhvalue_notctrlable__isCoherent;
	public void set_Dfhvalue_alterable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(301, 4, val, 0);;
			_dfhvalue_alterable__isValid = false;
		} else {
			set_Dfhvalue_alterable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_alterable() {
		if (!_dfhvalue_alterable__isValid) { _dfhvalue_alterable = super.getBinaryIntUNO(301,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_alterable__isValid = true; _dfhvalue_alterable__isCoherent = true;  } return _dfhvalue_alterable;
	}
	public int set_Dfhvalue_alterable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_alterable = val; _dfhvalue_alterable__isValid = true; _dfhvalue_alterable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_alterable() {if (_dfhvalue_alterable__isValid && !_dfhvalue_alterable__isCoherent) { _dfhvalue_alterable__isCoherent = true; super.setBinaryNormalized(301, 8, _dfhvalue_alterable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_alterable; public boolean _dfhvalue_alterable__isValid; private boolean _dfhvalue_alterable__isCoherent;
	public void set_Dfhvalue_notalterable(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(305, 4, val, 0);;
			_dfhvalue_notalterable__isValid = false;
		} else {
			set_Dfhvalue_notalterable(((Number)o).intValue());
		}
	}
	public int get_Dfhvalue_notalterable() {
		if (!_dfhvalue_notalterable__isValid) { _dfhvalue_notalterable = super.getBinaryIntUNO(305,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _dfhvalue_notalterable__isValid = true; _dfhvalue_notalterable__isCoherent = true;  } return _dfhvalue_notalterable;
	}
	public int set_Dfhvalue_notalterable(int val) {
		val = super.truncate( 8, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._dfhvalue_notalterable = val; _dfhvalue_notalterable__isValid = true; _dfhvalue_notalterable__isCoherent = false; return val; 
	}
	public final void synchronize_Dfhvalue_notalterable() {if (_dfhvalue_notalterable__isValid && !_dfhvalue_notalterable__isCoherent) { _dfhvalue_notalterable__isCoherent = true; super.setBinaryNormalized(305, 8, _dfhvalue_notalterable, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _dfhvalue_notalterable; public boolean _dfhvalue_notalterable__isValid; private boolean _dfhvalue_notalterable__isCoherent;
	public Ctpty ctpty = new Ctpty();
	public ByteBuffer get_Ctpty() {
		return ctpty.getBuffer();
	}
	public void set_Ctpty(ByteBuffer val) {
		ctpty.setBytes(val);
	}
	public CobolPointer get_Ctpty__Pointer() {
		return (ctpty != null) ? ctpty.pointerTo() : null;
	}
	public CobolPointer get_Ctpty__Pointer(int offset, int length) {
		return (ctpty != null) ? ctpty.pointerTo(offset,length) : null;
	}
	public void set_Ws_resp(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(309, 4, val, 0);;
			_ws_resp__isValid = false;
		} else {
			set_Ws_resp(((Number)o).intValue());
		}
	}
	public int get_Ws_resp() {
		if (!_ws_resp__isValid) { _ws_resp = super.getBinaryIntUNO(309,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _ws_resp__isValid = true; _ws_resp__isCoherent = true;  } return _ws_resp;
	}
	public ByteBuffer get_Ws_resp__AsNumericString() {
		synchronize_Ws_resp();
		return super.getBufferFromInteger(309,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS,9,0);
	}
	public int set_Ws_resp(int val) {
		val = super.truncate( 9, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._ws_resp = val; _ws_resp__isValid = true; _ws_resp__isCoherent = false; return val; 
	}
	public final void synchronize_Ws_resp() {if (_ws_resp__isValid && !_ws_resp__isCoherent) { _ws_resp__isCoherent = true; super.setBinaryNormalized(309, 9, _ws_resp, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _ws_resp; public boolean _ws_resp__isValid; private boolean _ws_resp__isCoherent;
	public CobolPointer get_Ws_resp__Pointer() {
		return super.pointerTo(309,4, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS,9,0);
	}
	public CobolPointer get_Ws_resp__Pointer(int offset, int length) {
		return super.pointerTo(309 + offset,Math.min(4 - offset, length), com.turrettech.p3cobol.lib.common.DataConstants.CobolType.GRP);
	}
	public void set_Ws_resp2(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(313, 4, val, 0);;
			_ws_resp2__isValid = false;
		} else {
			set_Ws_resp2(((Number)o).intValue());
		}
	}
	public int get_Ws_resp2() {
		if (!_ws_resp2__isValid) { _ws_resp2 = super.getBinaryIntUNO(313,4,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _ws_resp2__isValid = true; _ws_resp2__isCoherent = true;  } return _ws_resp2;
	}
	public int set_Ws_resp2(int val) {
		val = super.truncate( 9, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4); this._ws_resp2 = val; _ws_resp2__isValid = true; _ws_resp2__isCoherent = false; return val; 
	}
	public final void synchronize_Ws_resp2() {if (_ws_resp2__isValid && !_ws_resp2__isCoherent) { _ws_resp2__isCoherent = true; super.setBinaryNormalized(313, 9, _ws_resp2, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 4);} } public int _ws_resp2; public boolean _ws_resp2__isValid; private boolean _ws_resp2__isCoherent;
	public CobolPointer get_Ws_resp2__Pointer() {
		return super.pointerTo(313,4, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS,9,0);
	}
	public CobolPointer get_Ws_resp2__Pointer(int offset, int length) {
		return super.pointerTo(313 + offset,Math.min(4 - offset, length), com.turrettech.p3cobol.lib.common.DataConstants.CobolType.GRP);
	}
	public Dfheiblk dfheiblk = new Dfheiblk();
	public ByteBuffer get_Dfheiblk() {
		return dfheiblk.getBuffer();
	}
	public void set_Dfheiblk(ByteBuffer val) {
		dfheiblk.setBytes(val);
	}
	public CobolPointer get_Dfheiblk__Pointer() {
		return (dfheiblk != null) ? dfheiblk.pointerTo() : null;
	}
	public CobolPointer get_Dfheiblk__Pointer(int offset, int length) {
		return (dfheiblk != null) ? dfheiblk.pointerTo(offset,length) : null;
	}
	public void set_Eibcalen(Object o) {
		if (o instanceof ByteBuffer) {
			ByteBuffer val = (ByteBuffer)o;
			super.setBytes(317, 2, val, 0);;
		} else {
			set_Eibcalen(((Number)o).intValue());
		}
	}
	public int get_Eibcalen() {
		if (!_eibcalen__isValid) { _eibcalen = super.getBinaryIntUNO(317,2,com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS); _eibcalen__isValid = true; _eibcalen__isCoherent = true;  } return _eibcalen;
	}
	public int set_Eibcalen(int val) {
		val = super.truncate( 4, val, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 2); this._eibcalen = val; _eibcalen__isValid = true; _eibcalen__isCoherent = false; return val; 
	}
	public final void synchronize_Eibcalen() {if (_eibcalen__isValid && !_eibcalen__isCoherent) { _eibcalen__isCoherent = true; super.setBinaryNormalized(317, 4, _eibcalen, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS, 2);} } public int _eibcalen; public boolean _eibcalen__isValid; private boolean _eibcalen__isCoherent;
	public CobolPointer get_Eibcalen__Pointer() {
		return super.pointerTo(317,2, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.NBS,4,0);
	}
	public CobolPointer get_Eibcalen__Pointer(int offset, int length) {
		return super.pointerTo(317 + offset,Math.min(2 - offset, length), com.turrettech.p3cobol.lib.common.DataConstants.CobolType.GRP);
	}
	public void set_Eibaid(ByteBuffer val) {
		super.setBytes(319, 1, val, 0);;
	}
	public ByteBuffer get_Eibaid() {
		return super.toBuffer(319,1);
	}
	public CobolPointer get_Eibaid__Pointer() {
		return super.pointerTo(319,1, com.turrettech.p3cobol.lib.common.DataConstants.CobolType.ANS);
	}
	public CobolPointer get_Eibaid__Pointer(int offset, int length) {
		return super.pointerTo(319 + offset,Math.min(1 - offset, length), com.turrettech.p3cobol.lib.common.DataConstants.CobolType.GRP);
	}
	public void set_Dfhcommarea(int offset, int length, ByteBuffer val) {
		try {
			dfhcommarea.setBytesConstrained(offset, length, val);
		} catch (NullPointerException npe) { throw new P3AddressException("dfhcommarea"); }
	}
	public void set_Dfhcommarea(ByteBuffer val) {
		try { dfhcommarea.setBytes(0, 1, val, 0); } catch (NullPointerException npe) { throw new com.turrettech.p3cobol.lib.exceptions.P3AddressException("dfhcommarea"); };;
	}
	private ByteStore dfhcommarea;
	public void set_Dfhcommarea__Base() {
		dfhcommarea = ByteStore.newByteStore(1,DataConstants.CobolType.ANS);
	}
	public void set_Dfhcommarea__Base(CobolPointer p) {
		dfhcommarea = ByteStore.newByteStore(p);
	}
	public ByteBuffer get_Dfhcommarea() {
		try { return dfhcommarea.toBuffer(0,1); } catch (NullPointerException npe) { throw new com.turrettech.p3cobol.lib.exceptions.P3AddressException("dfhcommarea"); }
	}
	public Testbr() {
		super(320, DataConstants.DecimalType.DECIMAL);
		Throwable t = EXTERNAL_PROGRAM_DATA.getInitializerException();
		if (t != null) throw new ExceptionInInitializerError(t);
		getComparator().setLiterals(LITERALS);
	}
	boolean isInitialized = false;
	public void initialize() {
		if (isInitialized) return; else isInitialized = true;
		checkCharset(CobolCharset.NATIVE);
		_return_code__isValid = false;
		set_Return_code(0);
		set_Qwicsptr(com.turrettech.p3cobol.lib.CobolPointer.NULL);
		_qwicslen__isValid = false;
		_dfhresp_normal__isValid = false;
		set_Dfhresp_normal(0);
		_dfhresp_duprec__isValid = false;
		set_Dfhresp_duprec(14);
		_dfhresp_dupkey__isValid = false;
		set_Dfhresp_dupkey(15);
		_dfhresp_invreq__isValid = false;
		set_Dfhresp_invreq(16);
		_dfhresp_endfile__isValid = false;
		set_Dfhresp_endfile(20);
		_dfhresp_lengerr__isValid = false;
		set_Dfhresp_lengerr(22);
		_dfhresp_qiderr__isValid = false;
		set_Dfhresp_qiderr(44);
		_dfhresp_notfnd__isValid = false;
		set_Dfhresp_notfnd(13);
		_dfhresp_pgmiderr__isValid = false;
		set_Dfhresp_pgmiderr(27);
		_dfhresp_itemerr__isValid = false;
		set_Dfhresp_itemerr(26);
		_dfhvalue_client__isValid = false;
		set_Dfhvalue_client(1122);
		_dfhvalue_sender__isValid = false;
		set_Dfhvalue_sender(1045);
		_dfhvalue_log__isValid = false;
		set_Dfhvalue_log(54);
		_dfhvalue_nolog__isValid = false;
		set_Dfhvalue_nolog(55);
		_dfhvalue_readable__isValid = false;
		set_Dfhvalue_readable(35);
		_dfhvalue_notreadable__isValid = false;
		set_Dfhvalue_notreadable(36);
		_dfhvalue_updatable__isValid = false;
		set_Dfhvalue_updatable(37);
		_dfhvalue_notupdble__isValid = false;
		set_Dfhvalue_notupdble(38);
		_dfhvalue_ctrlable__isValid = false;
		set_Dfhvalue_ctrlable(56);
		_dfhvalue_notctrlable__isValid = false;
		set_Dfhvalue_notctrlable(57);
		_dfhvalue_alterable__isValid = false;
		set_Dfhvalue_alterable(52);
		_dfhvalue_notalterable__isValid = false;
		set_Dfhvalue_notalterable(53);
		ctpty.void_();
		ctpty.initialize();
		_ws_resp__isValid = false;
		set_Ws_resp(0);
		_ws_resp2__isValid = false;
		set_Ws_resp2(0);
		dfheiblk.void_();
		dfheiblk.initialize();
	}
	private void initializeLinkage() {
		dfhcommarea = null;
	}
	public static final InitialProgramDataInitializer EXTERNAL_PROGRAM_DATA = new InitialProgramDataInitializer(Testbr.class);
	public static final byte[] LITERALS = EXTERNAL_PROGRAM_DATA.getLiteralBytes();
	public static final ByteBuffer getLiteral(int offset, int length) {
		return ByteBuffer.wrap(LITERALS,offset,length);
	}
	public static final String getNationalLiteral(int offset, int length) {
		return DataUtil.utf8Charset.decode(getLiteral(offset, length)).toString();
	}
	public static final TreeMap<Integer,StatementLocation> STATEMENT_MAP = EXTERNAL_PROGRAM_DATA.getStatementMap();
	@Override
	public final TreeMap<Integer,StatementLocation> getStatementMap() {
		return STATEMENT_MAP;
	}
}
